### SAVE NEW CUSTOMER
POST http://localhost:8080/api/customers
Content-Type: application/json
Accept: application/json

{
  "name": "Euroform Kft",
  "vatNumber": "123456789",
  "registrationDate": "2020-05-10",
  "country": "Hungary",
  "postalCode": "2121",
  "city": "Budapest",
  "street": "Gyömrői",
  "streetNumber": "55",
  "currency": "EUR"
}

### FIND CUSTOMER BY ID
GET http://localhost:8080/api/customers/id/1



